### ISSUE TITLE
超过 36 小时就是 2 天了

### ISSUE THREAD

**Issue by AllanChain** [AllanChain/PKUHoleCommunity#13]
rt, 可查阅 1380860，超过 36 小时就显示 2 天比较反人类。

据考察为 [react-timeago](https://github.com/nmn/react-timeago/blob/master/src/index.js#L178) 的问题。可能歪果仁觉得这样没毛病？有没有必要修呢？

PS: 该库已一年未更新

**Comment by Yixuan-Wang** [comment]
重写[infrastructure/widget.js 第37行](https://github.com/pkuhelper-web/infrastructure/blob/99e6eac3bc5ba618fe00b763a3a71c1bc5875635/widgets.js#L37)的formatter可不可以呢？

**Comment by AllanChain** [comment]
很可惜，目测不行，`formatter` 只能被动接受 `value` 和 `unit`

**Comment by Yixuan-Wang** [comment]
哦，现在看懂了🤦‍♂️看了另外一个第三方包，也是从36小时起算2天🙃
