### ISSUE TITLE
路线规划（草稿）

### ISSUE THREAD

**Issue by AllanChain** [AllanChain/PKUHoleCommunity#16]
## 目前计划实现的功能

暂时列举，如要进一步讨论可以单开 Issue，如果可以的话就列在 project 里。

### 按照回复时间排序

这样可以将置顶和未读提醒“毕其功于一役”

### Beta 版测试功能

配置 CI，当发布如 `0.3.0b1` 的版本时，同时构建稳定版和 Beta 版。Beta 版的 `index.html` 命名为 `beta.html` 后，两个版本拷贝到一个文件夹中。正式版发布后，仅将其 `index.html` 拷贝为 `beta.html` 即可。

设置 Beta 版的目的是开发人员试用 Beta 版无大碍后再发布为正式版，提高稳定性。

### dependabot

是否给邮箱带来了“骚扰”？

## 项目未来

项目能不能继续下去仍是一个未知数，姑且走一步看一步。

## 项目定位

树洞网页版无疑取得了巨大的成功，占有较大的“市场份额”

贵校有很多动手能力强的同学，也有很多同学有着对网页版树洞的独特想法。这些想法有的是合理的、巧妙的，有的是脑洞太大不切实际的；有的完全可以在客户端完成，有的则需要联系后端。

然而官方并没有很好的处理同学们自己动手和表达想法的渠道。而且有很多呼声较高的功能迟迟不添加（毕竟一个人的精力有限）

社区版的目的是提供一个交流的平台，提供大家动手实现的方案。允许大家齐心协力构建自己的树洞客户端。

顺便也是让开发不再受制于个人的尝试。

### 项目名字

树洞网页社区版？社区网页版树洞？社区版网页树洞？树洞社区版？树洞网页版 CE？

### 关于推广

- 见到同学要求的网页版功能已实现时，予以回复推广
- 新功能开发完成后，以 change log 的形式推广

### 关于组织

我寻思凑齐 5 个 contributor 就开个组织吧。（如果号召不到 5 个，作为“社区版”大概率坚持不下去）

### 关于跟进官方

到了假期，官方很有可能会发布新功能，能否跟进是一大挑战。尤其是在修改了其代码风格的情况下（欲吐槽又止）

而且在官方维护人毕业之前，我相信项目仍然能得到较好的维护。如果官方在假期中维护得很好，社区版也就没有必要存在下去了。

**Comment by Yixuan-Wang** [comment]
可能还是得看PKUHelper团队和校方的意见吧……在灰色地带想有所发展可能还是太困难了……

**Comment by AllanChain** [comment]
我可能忘记说了。。<https://github.com/AllanChain/PKUHoleCommunity/commit/762abbd001bacb4d0a9909528d3731717e3f37d7> 已添加说明

**Comment by Yixuan-Wang** [comment]
> 我可能忘记说了。。[762abbd](https://github.com/AllanChain/PKUHoleCommunity/commit/762abbd001bacb4d0a9909528d3731717e3f37d7) 已添加说明

看到了，但这个官方回复还是比较模糊……按我的理解，《树洞规范》是否定一切**非官方**客户端的，官方回复中说的是“有权修改代码”，而不是“有权提供客户端服务”……因此仍然摆脱不了灰色地带……

网页版树洞之前也是第三方服务，后来被官方收编，前几天热榜似乎也是被官方收编了，这可能一定程度上能说明官方对于第三方服务的态度。我不太清楚树洞的运作方式，由于它的敏感性，我猜测可能是不允许任何“编外人员”参与开发的？但究竟界限在什么地方，我觉得官方的回复和规范都没有解释清楚……

**Comment by Yixuan-Wang** [comment]
另外话说dependantbot的通知问题有解决方案吗……半夜被轰醒……

**Comment by AllanChain** [comment]
> 这个官方回复还是比较模糊

<details><summary>的确如此，老官腔了</summary>

官方的规定确实迷幻，只要对网页版修改调试就可以算是非官方客户端，那么“有权实现自己的想法”就无从谈起。

回复中对禁止第三方客户端的限制有了“软化”，强调造成危害时会采取行动。故合理使用的情况属于某种“消极允许”？的确灰色..
</details>

#### 关于 dependabot

dependabot 逐渐和 GitHub 融合，所以现在看来如果只需要安全相关的话，完全可以卸载 dependabot，GitHub 也会提供安全警告。

我也是最近才意识到对邮箱的骚扰问题 \_(：3 」∠ )\_

最近几个项目，不管是否使用 dependabot，接连收到 websocket 的安全报警，还不止一封。。但是为什么官方项目没有报警呢？可能是关了？

**Comment by AllanChain** [comment]
dependabot 改成了早 7 点，仅安全更新，会安静一点。以后每发布一个 minor 版本最好更新一下依赖。

@Yixuan-Wang 以及以后对 dependabot 的 PR 可以 squash and merge，干净一点

**Comment by AllanChain** [comment]
Added to doc
