### ISSUE TITLE
关注列表按最后回复时间排序

### ISSUE THREAD

**Issue by Yixuan-Wang** [AllanChain/PKUHoleCommunity#19]
这个功能应该怎么实现呢？目前是先加载列表并渲染，再加载回复并计算最后回复时间……

**Comment by Yixuan-Wang** [comment]
也就是说，需要在回复加载完毕后，从子组件向父组件传值，触发父组件重新加载？

**Comment by AllanChain** [comment]
实现起来的确有点麻烦。。我觉得尽量不要先渲染，因为费时间

**Comment by Yixuan-Wang** [comment]
> 我觉得尽量不要先渲染
指的是尽量不要先渲染关注列表？还是回复？

**Comment by AllanChain** [comment]
等等，渲染的时间和网络 IO 时间相比应该还是网络时间长吧

**Comment by Yixuan-Wang** [comment]
网络 IO 时间肯定长一些……

**Comment by Yixuan-Wang** [comment]
（感觉 GitHub Issue 有点不适合 IM 节奏的讨论？邮箱已经爆炸了）

**Comment by Yixuan-Wang** [comment]
也许可以考虑引入 Redux 这样的状态管理？

**Comment by Yixuan-Wang** [comment]
思考了一下这个功能的实现……

目前时间线相关组件的层次结构：
Flow - FlowChunk - Context.Consumer - LazyLoad - FlowItemRow - FlowItem / Reply

洞的数据在 Flow 中获取，向右一层层传 prop，一直传到 FlowItemRow，也就是包含洞和全部回复的组件，在这一层才获取回复数据，并且计算最后回复时间，存储在 FlowItemRow 的 state 中。

如果**不改变上述流程**：
要想让 Flow 层拿到最后回复时间，可能的解决方案：
1. 一层层回调（太可怕了）
2. 用一个外部的 store 做简单的状态管理

另外，各个洞最后回复时间的计算也不是同步的。还需要确认所有的最后回复时间都已经计算完毕，才能考虑重新排序的问题。

假设 Flow 层能拿到最后回复时间，由于是要按最后回复时间排序，因此需要对洞的数组重新排序，改变 Flow 的 state，组件重新渲染。回复数据如果重新再获取一次，浪费了性能，因此之前回传的数据也应当包括所有的回复。但这样两次渲染（获取回复的渲染和重排的渲染）数据源完全不一样，整个组件的逻辑就有些混乱了。

如果**改变上述流程**，把加载回复挪到 Flow 中进行（也就是从异步获取回复变成同步获取），如果是从缓存中读取速度尚可，如果需要从服务器更新回复（尤其是现在存在神洞级别的置顶洞，第一个洞常常需要从服务器中获取更新），那么渲染过程可能会慢到难以忍受……

**Comment by Yixuan-Wang** [comment]
前端实现这一功能，感觉难度较大。

T大树洞提出的[后端解决方案](https://github.com/thuhole/thuhole-go-backend/issues/44)似乎更加简便易行：
> [后端]增加一个column叫last_reply_timestamp即可

但根据官方**鼓励树洞沉下去**的原则，官方维护的后端可能不会增加这一功能。

**Comment by Yixuan-Wang** [comment]
个人认为，回复分组更为可行，而且可能优于按最后回复时间排序的方式，准备另开 Issue 讨论。

**Comment by AllanChain** [comment]
> 但根据官方鼓励树洞沉下去的原则，官方维护的后端可能不会增加这一功能。

虽然但是，这会耽误事啊

---

（虽然工作量，但是）我的想法是，数据放到 Flow 中，返回 cache 中的数据和一个服务器同步的 `Promise`（如果频率过高，可能还要依次加 setimeout）。每个 FlowItem 在 Promise resolve 之后更新状态，Flow 则在所有都 resolve 后顶部显示按钮重新排序 。

此外，改变 cache 清洗方案，不去除关注的树洞
