### ISSUE TITLE
bug: 在 sidebar 的 box 中出现了多余的文本元素

### ISSUE THREAD

**Issue by Yixuan-Wang** [AllanChain/PKUHoleCommunity#2]
## 描述
![Snipaste_2020-04-30_21-13-58](https://user-images.githubusercontent.com/21151119/80714454-8a63c080-8b27-11ea-9d8d-566c1a4ac87a.png)

## 如何复现
点击树洞的内链访问到另一个树洞时（应该是未缓存的洞）

怀疑错误是在[这一处](https://github.com/AllanChain/PKUHoleCommunity/commit/919c54cc3071825d43d52e6f644b57d1550bdc05#diff-8eb6d99aa6435f2aee4763e9b3fadbcbR149)引入的，
commit 919c54，Flow.js，[149行](https://github.com/AllanChain/PKUHoleCommunity/blob/919c54cc3071825d43d52e6f644b57d1550bdc05/src/Flows.js#L149)

**Comment by AllanChain** [comment]
（卑微）已经修了，刚刚和记住浏览位置的功能一起发布。

话说为什么一个布尔类型也要加`!!`

**Comment by AllanChain** [comment]
> 话说为什么一个布尔类型也要加`!!`

因为内链进洞的话 `attention` 是 `0`，确须转换为 boolean
