### ISSUE TITLE
更换图标解决方案

### ISSUE THREAD

**Issue by Yixuan-Wang** [AllanChain/PKUHoleCommunity#26]
目前的图标解决方案是基于 [**icomoon**](https://icomoon.io/app/) 的，在网站上生成需要的图标字体。有以下不如意之处：
1. icomoon 图标很**少**。
2. 更换图标需要在原图标配置的基础上**重新打包**，而原图标的配置手头没有，需要手动输入。
3. 更新图标需要更换**图标字体**，是二进制文件，不利于 git 版本控制。

如果换用 [**fontawesome(fa)**](https://github.com/FortAwesome/react-fontawesome) 或 [**material design icons(mdi)**](https://github.com/Templarian/MaterialDesign-React) ：
1. 两种方案图标都较**多**，维护积极。
2. 都有 **React 包**，引入新图标只需修改组件的 prop。
3. 都支持 **tree-shaking**。

但换用图标可能对用户的观感有影响……

**Comment by AllanChain** [comment]
据我所知，mdi 要减少 bundle size 要用 JS SVG 的方法，先 import 再用。会比较麻烦。

ps：我之前对 Vuetify 项目试过用 JS SVG 方法收效甚微，不知道是什么原因，已被打击信心 orz

**Comment by Yixuan-Wang** [comment]
> 据我所知，mdi 要减少 bundle size 要用 JS SVG 的方法，先 import 再用。会比较麻烦。

现在的解决方案其实比 import 还麻烦，要到网上重新打包字体……现在只用了 24 个图标，转换成 import 工作量还不大……之后每次使用也只是添加一个 import，而不用打包新的字体文件……

ps: 大爱 mdi，不过还是谷歌原本 Material Design 图标最好，尤其是最初的[计划案](https://www.behance.net/gallery/33603855/Google-System-Icons)，由 mdi 社区新增的部分有设计不协调的。

**Comment by Yixuan-Wang** [comment]
![hole-icons](https://user-images.githubusercontent.com/21151119/86429112-2032ec00-bd21-11ea-8fe0-e1e303fe92c9.png)

**Comment by AllanChain** [comment]
mdi-bookmark-multiple mdi-plus-thick

**Comment by Yixuan-Wang** [comment]
试图在 mdi 里找到和原来样式一致的，结果特别不协调😭

**Comment by Yixuan-Wang** [comment]
找到一个库 [styled-icons](https://github.com/styled-icons/styled-icons)，也许可以做 icomoon 的 tree-shaking

**Comment by Yixuan-Wang** [comment]
svg 渲染效果堪忧（看来我是忘了我搭博客的时候遇到的灾难了😭）目前看起来还是乖乖地打包 icomoon 吧……
