### ISSUE TITLE
v0.2.5 Release (Plan)

### ISSUE THREAD

**Issue by AllanChain** [AllanChain/PKUHoleCommunity#27]
截至 976afe4

### Release Note (Draft)

因为有较多小功能的更新，跳过 v0.2.4。主要更新如下：

- 提供 beta 版，为新开发功能的实验地，登录状态与原社区版同步，地址为 https://allanchain.github.io/PKUHoleCommunity/beta.html
- 上线关注列表中搜索功能，在关注列表顶部搜索框输入关键词，即可搜索关注列表。（如果你是 RegEx 大佬，可以使用 `/.+/` 格式搜索）
- “社区版” 更加显眼
- 修复顶部 PKU Helper 其他应用的链接
- 去掉了默认的屏蔽词列表
- 跟进官方
- 修复一些警告

欢迎大家提出功能建议，或者参与到制作中来

**Comment by Yixuan-Wang** [comment]
## 更新功能列表

### 主要功能

- 屏蔽词（屏蔽不想看到的关键词）
- 在关注列表中搜索

### 修复提升

- 从一个洞内通过链接访问另一个洞，返回后记住原状态（即保留刷到的位置以及是否是倒序）
- 打开侧边栏以后主时间线不会滚动

### 界面/行为改变

- 侧边栏的标题不再透明，滚动条不会被标题遮盖
- 顶栏中的应用链接（成绩、不咕）目前可以正常访问，但访问时会回到官方版

## 其他

- 使用社区版同样应当遵守树洞规范。
- 社区版属于网页版树洞所说的“自行实现想法”，基于 GPLv3 在 GitHub 开源。不恰当使用此版本或利用此版本的漏洞对 PKU Helper 造成的不利影响由用户负责。作为社区版本，社区（No warranty）维护版本的安全，同时也欢迎基于社区版实现你的想法。
- 社区版提供 Beta 测试版本，登录状态与稳定版同步，更不稳定，试验性的新功能会优先推送到 Beta 版：[Beta版地址](https://allanchain.github.io/PKUHoleCommunity/beta.html)。
- 社区版欢迎大家提出功能建议，或者参与到社区版的维护和更新中。[GitHub 库地址](https://github.com/AllanChain/PKUHoleCommunity)，提出问题请到 [GitHub Issue](https://github.com/AllanChain/PKUHoleCommunity/issues)。
