### ISSUE TITLE
解决 beta 版本和 stable 版本之间的冲突

### ISSUE THREAD

**Issue by AllanChain** [AllanChain/PKUHoleCommunity#34]
### 问题简述

#21 中为了不必更改 beta 版本的 `PUBLIC_URL`，还可共用部分 assets，故部署与 `beta.html`。

但是这引起了 service worker 的冲突问题。react 默认使用 precache（在 service worker 安装时 cache 资源），而两个版本的 precache-manifest 的内容和名字不同，同时 `service-worker.js` 被 beta 版本覆盖，从而造成冲突。stable 版本的 precache-manifest 被污染，造成加载完成却白屏的现象。

同时，更改共有文件（如字体文件）也会引起问题。

### 解决方案

应该使两个版本彻底分离。目前看来，解决方案有：

- (**preferred**) 使用两个子文件夹，`stable/` 和 `beta/`，在 `index.html` 中增加 redirect
- (should work)另开仓库部署 beta 版本

### 注意事项

- 在问题解决前，**不得发布 beta 版本**
- 如要发布 beta 版本，则需在 ci 中选择不覆盖 service worker

### 如何过渡

在 `master` 和 `fix-ci-beta` 分支中，注释掉发布部分，使用 upload artifacts 测试。最后 squash merge

（虽然 fix-ci-beta 里的应该不会触发 master 的 workflow）

**Comment by AllanChain** [comment]
背景图片有 1.5M... 也分两个是不是不合适？

要不使用官方的图片链接？还可以加快访问速度。但是要涉及配置改动

**Comment by Yixuan-Wang** [comment]
> 背景图片有 1.5M... 也分两个是不是不合适？

我觉得 1.5M 还勉强可以忍受……？

**Comment by thuhole** [comment]
可以像https://github.com/thuhole/webhole 一样使用4个分支，在CI配置文件https://github.com/thuhole/webhole/blob/master/.travis.yml 里更改编译后的precache或/和service worker文件

**Comment by thuhole** [comment]
> > 背景图片有 1.5M... 也分两个是不是不合适？
> 
> 我觉得 1.5M 还勉强可以忍受……？

jsdelivr CDN是个好东西

**Comment by AllanChain** [comment]
@thuhole 用 jsdelivr 还不如用 pkuhelper :smirk: 有官方提供服务，当然要因地制宜嘛

日后还打算修改 IconMoon 字体，还是分开的好

**Comment by thuhole** [comment]
目前T大树洞采用了更成熟的方案部署不同分支，可参考：

https://github.com/thuhole/webhole/blob/faed990d5ab30bb51bbde85abf95ea2fc5dc420f/travis_deploy.sh#L7-L13
