### ISSUE TITLE
关注列表分组

### ISSUE THREAD

**Issue by Yixuan-Wang** [AllanChain/PKUHoleCommunity#35]
没能收集到足够的关注列表组成的反馈……只能口胡一波……

关注在树洞里是一个非常模糊的概念，它可能表示以下意义：
1. 点赞，+1。
2. 吃瓜，关注（等待话题**实时**更新）。
3. 参与讨论（回复后自动关注）。
4. 订阅（等待话题（比如个人经历的分享、针对某个问题的答疑等）**定期**更新）。
5. 收集（一次性发出的实用信息，比如课程测评，收集起来留待日后查阅）
6. 留念（自己在这个洞里留下了回忆，偶尔翻一翻追忆一下）
7. 神洞

因此关注列表内部可能确实存在分组的需求。

**Comment by Yixuan-Wang** [comment]
分组倒不必复杂化，可以仅按照两个维度分类分组：是否**需要常看**，是否**回复活跃**。

## 常看且回复活跃
**吃瓜**、**参与讨论**的，应该*置顶*。这一类洞一般不会太多，因此即使不按最后回复时间排序，置顶后也能及时获取到更新，而不需要向下翻找太久。

## 常看且回复不活跃
**订阅**、**收集**的，应该在*第二位*。对于这样的洞，查看次数实际上会少于前一类（因为它们不再更新了），因此放在第二位，也不需要太多的翻找。而且加入关注列表搜索以后，寻找这一类洞的速度会快一些。

## 不常看且回复不活跃
**点赞**、**留念**的，应该在*第三位*。由于看的频率低，自然排在后面。但这些洞本身比神洞对个人具有更多价值，还是应该优先于神洞。

## 不常看且回复活跃
树洞最神奇的存在，**神洞**。

**Comment by AllanChain** [comment]
mark, star, subscribe?
