### ISSUE TITLE
【Feature Request】兼容T大树洞，或者兼容双token登录

### ISSUE THREAD

**Issue by thuhole** [AllanChain/PKUHoleCommunity#38]

**Comment by thuhole** [comment]
主要区别，除了API的URL之外，应该就是T大树洞增加了折叠和Markdown的功能

**Comment by AllanChain** [comment]
TP-LINK 的确是好事。但是 TP 树洞后台的演进速度是不一样的。为了使一套前端兼容 TP 树洞，T 大树洞后端的发展会受到制约。

同时 P 大树洞无论是官方版还是社区版都应该兼顾到 App 端的改动和用户体验。社区版目前为止的改进主要也是针对**易用性**的。我个人而言，不愿意在在较大功能上和官方版叫板，毕竟官方维护同学都不容易。

（还有 #19 正在筹划的功能肯定和 T 大不兼容）

当然，如果 T 大愿意考虑 P大树洞的兼容性，把 TP-LINK 树洞定位为 T 大树洞“官方”主导发起，P 大“社会人士”参与的树洞客户端，我也支持项目合流。（实际上是懒得大改，逃\~）

**Comment by thuhole** [comment]
> TP-LINK 的确是好事。但是 TP 树洞后台的演进速度是不一样的。为了使一套前端兼容 TP 树洞，T 大树洞后端的发展会受到制约。
> 
> 同时 P 大树洞无论是官方版还是社区版都应该兼顾到 App 端的改动和用户体验。社区版目前为止的改进主要也是针对**易用性**的。我个人而言，不愿意在在较大功能上和官方版叫板，毕竟官方维护同学都不容易。
> 
> （还有 #19 正在筹划的功能肯定和 T 大不兼容）
> 
> 当然，如果 T 大愿意考虑 P大树洞的兼容性，把 TP-LINK 树洞定位为 T 大树洞“官方”主导发起，P 大“社会人士”参与的树洞客户端，我也支持项目合流。（实际上是懒得大改，逃~）

实际上T大树洞的后端已经不会再有特别重大的改动了。

大改应该不会特别大，也就100多个commit。考虑到T大树洞实际上也是某种意义上的“社区版”，这两个版本的代码merge后，针对易用性的开发可能可以合作和同步。
接下来一段时间我们这边尝试merge一下吧。

**Comment by thuhole** [comment]
刚刚花了一个小时把社区版的功能都merge到了https://dev.thuhole.com 了

**Comment by AllanChain** [comment]
<details><summary>虽然</summary>
我个人不喜欢 Flutter 以及一套代码管 Web 端和移动端的操作
</details>

Anyway, done in https://github.com/thuhole/webhole-next
