### ISSUE TITLE
图标和背景图加载不出

### ISSUE THREAD

**Issue by Xavier-YangCN** [AllanChain/PKUHoleCommunity#42]
如题。关注回复等图标以及背景图片日常加载不出来，刷新网页重启浏览器都没效果。在官方版上没有此问题。

**Comment by AllanChain** [comment]
国内部分地区 github pages 挂了，正在打算迁移到 gitee :cry:

**Comment by Xavier-YangCN** [comment]
哦哦...挂上梯子好像就可以了:)thx

**Comment by Yixuan-Wang** [comment]
使用北大校园网目前也是可以的
