### ISSUE TITLE
Hello From PKUHollow

### ISSUE THREAD

**Issue by pkuhollow** [AllanChain/PKUHoleCommunity#53]
Hello World!

新的 [未名树洞](https://pkuhollow.com) 欢迎社区版的贡献和加入。

未名树洞的大门永远对每一位PKUer敞开，无论是已毕业的校友，还是在校内奋斗的每一位同学。树洞中的疑惑、同学之间的情感、宝贵的人生经验都不因毕业而消逝，我们希望未名树洞成为大家共同的记忆，和PKUer之间薪火相传的桥梁。未名树洞由热爱树洞的学生创建，但同时属于未名的每一位用户，由全体用户共同提出树洞规范的建议和发展的方向，没有口袋规则，没有无端的封禁。即便由非官方管理，未名树洞致力于守护树洞的大门，以严密的技术手段保护每一名用户的个人信息与隐私。

**Comment by AllanChain** [comment]
虽然但是，我个人一直很反感在 Issue 区打广告（还与该仓库的代码几乎没关系）的行为。

**Comment by pkuhollow** [comment]
对不起。

为您带来困扰，非常抱歉~
