### ISSUE TITLE
安卓手机版Firefox不能选择图片

### ISSUE THREAD

**Issue by 1900011604** [AllanChain/PKUHoleCommunity#55]
见树洞1916416

**Comment by AllanChain** [comment]
来错地方了 🐶 。不过确实官方树洞网页端已经停止维护。

ps: chrome android 选择文件有时候也会卡很久

pps: ff android 导入个 token 直接闪退，应该是 ff 的问题吧 🤷‍♂️

**Comment by 1900011604** [comment]
emmmm 导入token没问题的，但是选择文件卡顿在手机APP Edge也会有。您说的更新前是哪一次啊

**Comment by AllanChain** [comment]
> 更新前是哪一次啊

本项目还在积极更新的时候 :dog: 拿 ff 试过。但是今天 ff 看起来不太开心，或者是我手机性能不够，我这里导入 token、选择文件都闪退

**Comment by 1900011604** [comment]
是不是火狐版本问题？最新版本在这里，别用啥华为应用市场之类的啦。

https://github.com/mozilla-mobile/fenix/releases

**Comment by AllanChain** [comment]
亲测 Firefox 84.1.1 闪退，Firefox 85.0.0-beta.3 没问题。

Related: mozilla-mobile/fenix#17141

那么这个问题就愉快地结束了

**Comment by 1900011604** [comment]
啊啊啊………我就是85.0beta3啊

**Comment by AllanChain** [comment]
@1900011604 已证实该问题与网页无关，更与本项目无关。如仍有问题，请按照其社区守则在 fenix 那里开 Issue
