### ISSUE TITLE
想问一下北大是官方支持树洞的运营嘛

### ISSUE THREAD

**Issue by llzmgjzhy** [AllanChain/PKUHoleCommunity#69]
我也想将树洞迁移到本校，但在学校审批受阻，想了解一下北大树洞怎么被学校支持的

**Comment by Alice-space** [comment]
请联系 contact@treehollow.net 团队联系邮箱

**Comment by AllanChain** [comment]
现在北大的树洞是官方运营（垃圾的很，bug 不修），但原先的树洞学生开发者都被迫退出，GitHub 上的仓库也已删除。北大树洞学生参与开发期间，熊典和肖元安是最有名有姓的两位，但我没有他们的联系方式。

目前我不知道官方支持 + 学生维护的案例。可以问问清华树洞或楼上，他们也在做这个方向。

**Comment by AllanChain** [comment]
Closing as resolved
