### ISSUE TITLE
有没有考虑对删除洞进行自动备份+页面显示

### ISSUE THREAD

**Issue by zhuozhiyongde** [AllanChain/PKUHoleCommunity#72]
如题，本项目已经积累了一定用户量，如果可以**询问用户是否自愿加入备份计划**，并得到一定量的Token，理论上即可对全天所有树洞进行分钟级别监测，并在其他地方备份树洞内容。
据我所知，自树洞开洞以来，所有文本数据在10GB这个数量级。而且即使是被删除的洞，图片资源也仍然可以通过URL访问。
我之前做过 [PKU NEWS](https://arthals.ink/?p=95)（一个树洞热榜，每半小时更新一次，可以依据关注、恢复以及热度来排序，因被乐坛已下架）以及 PKU Backup（小时级备份树洞，备份率达99%，已删除） 但后来因为脚本达到每天万次（每半小时请求100页+约200条监测列表）的请求量，被计算中心定位并封号（现已解封），就有了这个idea。
如果能够召一定量集用户分散请求量，理论上就可以避免被定位非法请求请喝茶。数据量上来说，每天几千条树洞带上回复，这种原始但有效的备份方法应当是可行的。
考虑到qy现在删帖速度越来越快，对于每条树洞的持续更新时间可以设到很小，比如十分钟，那么每天1440次请求最新的几张整体页面，一天假设是3000条树洞，每条请求十次评论，则整体API请求次数大概也就是数万级别。如果完全不考虑回复，只考虑主贴内容，则请求量则可控制在数千级别。
已知：树洞根据Token有反爬，IP似乎也有一定限制，可能要考虑上IP池。
以上仅为个人想法，具体操作能否实现、愿不愿意实现均未知，仅供参考。

**Comment by Yixuan-Wang** [comment]
个人认为，本项目获取树洞用户 Token **仅用于正常浏览**。获取乃至存储用户 Token 以用于除**正常浏览外的用途**（即使在用户自愿授权的前提下）不属于这一项目考虑添加的功能。

**Comment by AllanChain** [comment]
我基本同意 @Yixuan-Wang 的看法，这个不属于本项目的范围。以下内容是均以个人身份而非项目维护者身份发表。

首先分布式备份的操作很久之前就[有人做过](https://github.com/e83imb/PKU_Hole_Helper)了，可以考虑和 @e83imb 合作。这个方案完全基于官方客户端，愿意用的人可能更多。

对于备份树洞，我的看法是没必要追求高备份率。很多时候（指日常）青盐的删贴是有助于维护正常的社区氛围的，很多帖子确实该删。我们学生关心的其实是一些青盐试图“灭火”的重大的舆情事件。这个时候虽然删贴频率高，但好在关心的主要内容在主贴中，备份回复不太重要。所以只需在集中时间抓取主贴即可，这样一个人操作足够。事实上因为近期的一些事件，我 prototype 了 [hole-martyr](https://github.com/AllanChain/hole-martyr)，如果对项目有兴趣可以到那里讨论。

再次说明以上均为个人身份。

Closing as won't fix.

**Comment by zhuozhiyongde** [comment]
get 感谢恢复。
