### ISSUE TITLE
登录后显示:TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by intreeeee** [AllanChain/PKUHoleCommunity#73]
如题，网页版也有同样的问题,控制台错误描述：

```
TypeError: Cannot read properties of undefined (reading 'length')
    at Flows.js:1179:41
n @ Flows.js:1165
widgets.js:126 
        
       loading appswitcher items failed
(匿名) @ widgets.js:126
widgets.js:127 TypeError: Failed to fetch
    at widgets.js:108:13
(匿名) @ widgets.js:127
```

**Comment by AllanChain** [comment]
我记得 appswitcher 之前是链接到了xmcp 的服务器上，但是后来 xmcp 换了域名，就获取不到了。

至于修复的话也没啥很大必要。要么就删掉动态更新 appswitcher 的代码。

**Comment by Hovennnnn** [comment]
@intreeeee 
哥们似乎跟我是同个问题，请问解决了吗？
[https://github.com/AllanChain/PKUHoleCommunity/issues/74](https://github.com/AllanChain/PKUHoleCommunity/issues/74)

**Comment by intreeeee** [comment]
并未，现在一直在用同学的token登录树洞，by the way，青研和计算中心我都问过了，但都没有答复的...如果不是大规模得出现问题，很难指望他们



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月6日(周五) 中午1:05
收件人: ***@***.***&gt;;
抄送: "JiLong ***@***.******@***.***&gt;;
主题: Re: [AllanChain/PKUHoleCommunity] 登录后显示:TypeError: Cannot read property 'length' of undefined (Issue #73)




 
@intreeeee
 哥们似乎跟我是同个问题，请问解决了吗？
 #74
